version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip -o terraform.zip -d /usr/local/bin
      - rm terraform.zip
      - terraform version
      - aws --version

  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init -reconfigure
      - echo "Validating Terraform..."
      - terraform validate
      - echo "Planning Terraform..."
      - terraform plan -out=tfplan.out
      - echo "Applying Terraform..."
      - terraform apply -auto-approve tfplan.out

  post_build:
    commands:
      - echo "Terraform apply complete."
      - terraform output
