# buildspec.yml
version: 0.2

env:
  variables:
    TF_VERSION: "1.8.5"  # Updated to a recent stable Terraform version
    TF_PATH: "/usr/local/bin"
    TF_STATE_BUCKET: "your-terraform-state-bucket-name"    # Replace with your actual S3 bucket
    TF_STATE_LOCK_TABLE: "your-terraform-state-lock-table"  # Replace with your actual DynamoDB table
    ENV_NAME: "dev"                                         # Used for the S3 key path

phases:
  install:
    commands:
      - echo "Installing Terraform CLI version ${TF_VERSION}..."
      - curl -sS -o terraform.zip "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - unzip -o terraform.zip -d "${TF_PATH}"
      - rm terraform.zip
      - chmod +x "${TF_PATH}/terraform"
      - echo "Terraform version:"
      - terraform version
      - echo "Checking AWS CLI version..."
      - aws --version
      - echo "Build region is: $AWS_REGION"

  pre_build:
    commands:
      - echo "Assuming Terraform configuration (main.tf, variables.tf) is in the current directory..."
      # If your Terraform code is in a subdirectory (e.g., 'terraform/'), uncomment and use: cd terraform/

      - echo "Checking for existing DynamoDB state lock table: ${TF_STATE_LOCK_TABLE} in ${AWS_REGION}..."
      - |
        if ! aws dynamodb describe-table --table-name "${TF_STATE_LOCK_TABLE}" --region "${AWS_REGION}" 2>/dev/null; then
          echo "DynamoDB table ${TF_STATE_LOCK_TABLE} does not exist. Creating now..."
          aws dynamodb create-table \
            --table-name "${TF_STATE_LOCK_TABLE}" \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
            --region "${AWS_REGION}"
          echo "Waiting for DynamoDB table ${TF_STATE_LOCK_TABLE} to become active..."
          aws dynamodb wait table-exists --table-name "${TF_STATE_LOCK_TABLE}" --region "${AWS_REGION}"
          echo "DynamoDB table ${TF_STATE_LOCK_TABLE} created successfully."
        else
          echo "DynamoDB table ${TF_STATE_LOCK_TABLE} already exists."
        fi

      - echo "Initializing Terraform with S3 backend..."
      - terraform init \
          -backend-config="bucket=${TF_STATE_BUCKET}" \
          -backend-config="key=${ENV_NAME}/terraform.tfstate" \
          -backend-config="dynamodb_table=${TF_STATE_LOCK_TABLE}" \
          -backend-config="region=${AWS_REGION}" \
          -reconfigure

  build:
    commands:
      - echo "Validating Terraform configuration..."
      - terraform validate
      - echo "Generating Terraform execution plan..."
      - terraform plan -lock=true -out=tfplan.out
      - echo "Applying Terraform plan..."
      - terraform apply -lock=true -auto-approve tfplan.out

  post_build:
    commands:
      - echo "Terraform deployment complete."
      - |
        echo "Fetching output values..."
        # These outputs are defined in main.tf and will be available after apply
        terraform output -raw eks_cluster_name_output || echo "Output 'eks_cluster_name_output' not found."
        terraform output -raw db_endpoint_address || echo "Output 'db_endpoint_address' not found."
